server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: ad-service
          uri: lb://AD-SERVICE
          predicates:
            - Path=/api/v1/ads/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/v1/reviews/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: user-service
      paths-to-match: /api/v1/users/**
    - group: ad-service
      paths-to-match: /api/v1/ads/**
    - group: package-service
      paths-to-match: /api/v1/packages/**
    - group: review-service
      paths-to-match: /api/v1/reviews/**
    - group: payment-service
      paths-to-match: /api/v1/payments/**
