server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: ad-service
          uri: lb://AD-SERVICE
          predicates:
            - Path=/api/v1/ads/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/v1/review/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
